name: SData client library build

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: debug build
      shell: pwsh
      run: |
        .\Build.ps1

    - name: release build
      shell: pwsh
      run: |
        .\Build.ps1 -Debug $false

    - name: store release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: dist\Release
        if-no-files-found: error

    - name: store debug artifacts
      uses: actions/upload-artifact@v4
      with:
        name: debug
        path: dist\Debug
        if-no-files-found: error
