name: SData client library build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    
    # - name: Setup NuGet
    #   uses: nuget/setup-nuget@v1
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
    
    # - name: Restore Packages
    #   run: nuget restore DotNetSDataClient.sln
    
    - name: build
      shell: pwsh
      run: |
        .\Build.ps1